version: "3.8"

# NOTE: As this is a non-root container, the mounted files and directories must
#       have the proper permissions for the UID 1001.

services:
  redis:
    image: bitnami/redis:7.0.10
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
      - ./docker_volume/redis/data:/bitnami/redis/data
    command: ["redis-server", "./redis.conf"]
